### PR TITLE
Add "Play with an additional deck" option

### PR DESCRIPTION
**Pull request by propstg**
Thanks for the awesome script! This PR just (crudely) makes it so the deck never runs out of cards.

### CODE REVIEW

**Comment by Meek97** [comment]
Just by taking a look at the commits - I guess this works. 
But unless something isn't working as intended - the play card pile is suppose to merge back into the draw deck once the draw pile drops below a certain number of cards so I'm not sure what this does differently.
If you can explain - then I don't see any reason to not merge this into the workshop version

**Comment by propstg** [comment]
Yeah, in the normal mode, merging the play card pile back into the draw deck does work. This is more for when the draw deck runs out of cards after the play card pile has already been merged back into it.

However, thinking about it more, reworking this into a "play with an additional deck" checkbox and just starting the game with 2 decks would be more straightforward and would probably cover our group's needs. I can update the PR with these changes tomorrow, if that approach sounds better to you.

**Comment by Meek97** [comment]
If the script is properly reshuffling the cards when the draw pile runs low, then I'm just not understanding what spawning in more cards instead does differently

**Comment by Meek97** [comment]
Playing with an additional deck is a house rule that actually makes sense. because then you have double the quantity of cards such at wilds, skips, ect.

**Comment by propstg** [comment]
> Playing with an additional deck is a house rule that actually makes sense. because then you have double the quantity of cards such at wilds, skips, ect.

Agreed. Updated.

**Comment by Meek97** [comment]
Re-opening so I can merge changes to main branch

**Pull request merged**
